defmodule SocialPomodoro.RoomNameGenerator do
  @moduledoc """
  Generates random, peaceful room names for pomodoro sessions.
  Pattern: Adjective + Adjective + Noun (e.g., "Calm-Sunny-Garden")
  Total combinations: 50 × 50 × 100 = 250,000 unique names
  """

  # First adjective list (50 words) - focus on atmosphere/mood
  @adjectives_1 [
    "Quiet",
    "Calm",
    "Gentle",
    "Peaceful",
    "Soft",
    "Bright",
    "Warm",
    "Cool",
    "Fresh",
    "Clear",
    "Deep",
    "Light",
    "Pure",
    "Still",
    "Smooth",
    "Sweet",
    "Crisp",
    "Mellow",
    "Tender",
    "Mild",
    "Hushed",
    "Silent",
    "Tranquil",
    "Serene",
    "Placid",
    "Zen",
    "Cozy",
    "Snug",
    "Comfy",
    "Pleasant",
    "Dreamy",
    "Misty",
    "Hazy",
    "Airy",
    "Breezy",
    "Flowing",
    "Steady",
    "Balanced",
    "Centered",
    "Grounded",
    "Focused",
    "Mindful",
    "Present",
    "Aware",
    "Patient",
    "Careful",
    "Thoughtful",
    "Wise",
    "Kind",
    "Noble"
  ]

  # Second adjective list (50 words) - focus on time/nature/quality
  @adjectives_2 [
    "Morning",
    "Evening",
    "Midnight",
    "Dawn",
    "Dusk",
    "Twilight",
    "Afternoon",
    "Early",
    "Late",
    "Timeless",
    "Golden",
    "Silver",
    "Bronze",
    "Amber",
    "Ivory",
    "Pearl",
    "Crystal",
    "Velvet",
    "Silk",
    "Marble",
    "Wooden",
    "Stone",
    "Brick",
    "Glass",
    "Paper",
    "Sunny",
    "Cloudy",
    "Starlit",
    "Moonlit",
    "Shadowy",
    "Rainy",
    "Snowy",
    "Windy",
    "Stormy",
    "Foggy",
    "Frosty",
    "Dewy",
    "Verdant",
    "Lush",
    "Blooming",
    "Ancient",
    "Modern",
    "Classic",
    "Vintage",
    "Rustic",
    "Urban",
    "Coastal",
    "Mountain",
    "Forest",
    "Desert"
  ]

  # Noun list (100 words) - places, objects, and concepts that evoke focus/calm
  @nouns [
    "Library",
    "Study",
    "Office",
    "Studio",
    "Workshop",
    "Atelier",
    "Lab",
    "Den",
    "Loft",
    "Nook",
    "Corner",
    "Alcove",
    "Booth",
    "Cabin",
    "Cottage",
    "Lodge",
    "Retreat",
    "Hideaway",
    "Sanctuary",
    "Haven",
    "Refuge",
    "Oasis",
    "Garden",
    "Courtyard",
    "Terrace",
    "Balcony",
    "Porch",
    "Veranda",
    "Patio",
    "Deck",
    "Cafe",
    "Bistro",
    "Teahouse",
    "Coffeehouse",
    "Bakery",
    "Kitchen",
    "Pantry",
    "Cellar",
    "Vault",
    "Chamber",
    "Hall",
    "Gallery",
    "Museum",
    "Archive",
    "Tower",
    "Lighthouse",
    "Observatory",
    "Station",
    "Terminal",
    "Port",
    "Harbor",
    "Bay",
    "Cove",
    "Inlet",
    "Shore",
    "Beach",
    "Island",
    "Peninsula",
    "Valley",
    "Canyon",
    "Mesa",
    "Ridge",
    "Peak",
    "Summit",
    "Plateau",
    "Meadow",
    "Field",
    "Grove",
    "Orchard",
    "Vineyard",
    "Park",
    "Square",
    "Plaza",
    "Avenue",
    "Lane",
    "Path",
    "Trail",
    "Bridge",
    "Fountain",
    "Pond",
    "Lake",
    "Stream",
    "Creek",
    "River",
    "Falls",
    "Spring",
    "Well",
    "Forest",
    "Woods",
    "Thicket",
    "Clearing",
    "Glade",
    "Dell",
    "Hollow",
    "Knoll",
    "Hill",
    "Bluff",
    "Cliff",
    "Cave",
    "Grotto"
  ]

  @doc """
  Generates a random room name by combining two adjectives and a noun with hyphens.
  Pattern: Adjective-Adjective-Noun

  ## Examples

      iex> SocialPomodoro.RoomNameGenerator.generate()
      "Calm-Sunny-Garden"

  """
  def generate do
    adj1 = Enum.random(@adjectives_1)
    adj2 = Enum.random(@adjectives_2)
    noun = Enum.random(@nouns)

    "#{adj1}-#{adj2}-#{noun}"
  end
end
