name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            git \
            build-essential \
            autoconf \
            libssl-dev \
            libncurses5-dev \
            inotify-tools \
            postgresql-client

      - name: Install asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
          echo '. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc
          echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc

      - name: Install Erlang and Elixir via asdf
        run: |
          source ~/.asdf/asdf.sh
          asdf plugin add erlang
          asdf plugin add elixir
          asdf install erlang 26.2.5
          asdf install elixir 1.17.2-otp-26
          asdf global erlang 26.2.5
          asdf global elixir 1.17.2-otp-26
          mix local.hex --force
          mix local.rebar --force

      - name: Install Mix dependencies
        run: |
          source ~/.asdf/asdf.sh
          mix deps.get

      - name: Setup assets
        run: |
          source ~/.asdf/asdf.sh
          mix assets.setup
